# Generated by Django 5.2.3 on 2025-06-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieinfo",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
