# Generated by Django 5.2.3 on 2025-06-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_censorinfo_movieinfo_censor_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieinfo",
            name="directed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directed_by",
                to="movies.director",
            ),
        ),
    ]
